// ------- product-modal-icons ---------
import icon1 from "../../assets/product-modal-icons/icon1.png";
import icon2 from "../../assets/product-modal-icons/icon2.png";
import icon3 from "../../assets/product-modal-icons/icon3.png";
import icon4 from "../../assets/product-modal-icons/icon4.png";
import icon5 from "../../assets/product-modal-icons/icon5.png";
import icon6 from "../../assets/product-modal-icons/icon6.png";
import icon7 from "../../assets/product-modal-icons/icon7.png";

import pizza1 from "../../assets/products/pizza1.png";
import pizza2 from "../../assets/products/pizza2.png";
import pizza3 from "../../assets/products/pizza3.png";
import pizza4 from "../../assets/products/pizza4.png";
import sushi1 from "../../assets/products/sushi1.png";
import sushi2 from "../../assets/products/sushi2.png";
import sushi3 from "../../assets/products/sushi3.png";
import sushi4 from "../../assets/products/sushi4.png";
import zapusk1 from "../../assets/products/zapusk1.png";
import zapusk2 from "../../assets/products/zapusk2.png";
import zapusk3 from "../../assets/products/zapusk3.png";
import zapusk4 from "../../assets/products/zapusk4.png";
import zapusk5 from "../../assets/products/zapusk5.png";
import dessert1 from "../../assets/products/dessert1.png";
import dessert2 from "../../assets/products/dessert2.png";
import dessert3 from "../../assets/products/dessert3.png";
import dessert4 from "../../assets/products/dessert4.png";
import dessert5 from "../../assets/products/dessert5.png";
import uuid from "react-uuid";

export const PizzaData = [
  {
    img: pizza1,
    title: "Чикен Сладкий Чили",
    text: "Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный соу...",
    price: "456",
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza2,
    title: "EASY PEASY огуречный расколбас",
    text: "Курица, Лук, Перец Халапеньо...",
    price: "594",
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza3,
    title: "EASY PEASY чикен а-ля хрен",
    text: "Курица, Лук, Соус Карбонара,...",
    price: "249",
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza4,
    title: "4 сезона",
    text: "Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...",
    price: "630",
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza1,
    title: "Чикен Сладкий Чили",
    text: "Курица, Лук, Перец Халапеньо, Сыр Моцарелла, Томатный соу...",
    price: "456",
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza2,
    title: "EASY PEASY огуречный расколбас",
    text: "Курица, Лук, Перец Халапеньо...",
    price: "594",
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza3,
    title: "EASY PEASY чикен а-ля хрен",
    text: "Курица, Лук, Соус Карбонара,...",
    price: "249",
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: pizza4,
    title: "4 сезона",
    text: "Бекон, Ветчина, Грибы, Курица, Лук, Маслины, Огурцы мари...",
    price: "630",
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
];

export const SushiData = [
  {
    img: sushi1,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi2,
    title: "Филадельфия крем-брюле",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 395,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi3,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi4,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi4,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi3,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi1,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: sushi2,
    title: "Филадельфия крем-брюле",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 395,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
];

export const ZapuskData = [
  {
    img: zapusk1,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk2,
    title: "Филадельфия крем-брюле",
    text: "Сливочный сыр, семга татаки с тростниковым сахаром, соус у...",
    price: 395,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk3,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk4,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk4,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk3,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk5,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: zapusk5,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
];

export const DessertsData = [
  {
    img: dessert1,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert2,
    title: "Филадельфия крем-брюле",
    text: "Сливочный сыр, семга татаки с тростниковым сахаром, соус у...",
    price: 395,
    isNew: true,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert3,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert4,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert5,
    title: "Тигр мама",
    text: "Тигровая креветка, огурец, авокадо, соус Айоли, рис, ик...",
    price: 525,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert1,
    title: "Супер Филадельфия",
    text: "Действительно много семги, сливочный сыр, огурец, рис, н...",
    price: 425,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert2,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
  {
    img: dessert3,
    title: "Филадельфия кранч",
    text: "Семга, рис, сыр креметто, соус унаги, креветка, авокадо, чип...",
    price: 475,
    isNew: false,
    defaultSize: 23,
    desc: "Lorem ipsum dolor sit.",
    count: 0,
    id: uuid(),
  },
];

export const productModalIcons = [
  icon1,
  icon2,
  icon3,
  icon4,
  icon5,
  icon6,
  icon7,
];

// export const Data = [
//   {
//     img: ,
//     title: "",
//     text: "",
//     price: ,
//     isNew: true,
//   },
// ]
