import uuid from "react-uuid";

export const filterMenus = ["Общее", "Сыр", "Мясо", "Компонент"];

export const filterData = [
  { type: "Общее", name: "Хит", id: uuid() },
  { type: "Общее", name: "Новинка", id: uuid() },
  { type: "Общее", name: "С мясом", id: uuid() },
  { type: "Общее", name: "Вегетарианская", id: uuid() },
  { type: "Общее", name: "С курицей", id: uuid() },
  { type: "Общее", name: "Без лука", id: uuid() },
  { type: "Общее", name: "С грибами", id: uuid() },
  { type: "Общее", name: "С морепродуктами", id: uuid() },
  { type: "Общее", name: "Барбекью", id: uuid() },
  { type: "Сыр", name: "Реджанито", id: uuid() },
  { type: "Сыр", name: "Моцарелла", id: uuid() },
  { type: "Сыр", name: "Чеддер", id: uuid() },
  { type: "Сыр", name: "С голубой плесенью", id: uuid() },
  { type: "Сыр", name: "Смесь итальянских сыров", id: uuid() },
  { type: "Сыр", name: "Мягкий молодой сыр", id: uuid() },
  { type: "Мясо", name: "Пепперони", id: uuid() },
  { type: "Мясо", name: "Свинина", id: uuid() },
  { type: "Мясо", name: "Ветчина", id: uuid() },
  { type: "Мясо", name: "Бекон", id: uuid() },
  { type: "Мясо", name: "Говядина", id: uuid() },
  { type: "Мясо", name: "Чоризо", id: uuid() },
  { type: "Мясо", name: "Колбаски", id: uuid() },
  { type: "Мясо", name: "Куриная грудка", id: uuid() },
  { type: "Мясо", name: "Хит", id: uuid() },
  { type: "Компонент", name: "Креветка", id: uuid() },
  { type: "Компонент", name: "Ананасы", id: uuid() },
  { type: "Компонент", name: "Шампиньоны", id: uuid() },
  { type: "Компонент", name: "Перец халапеньо", id: uuid() },
  { type: "Компонент", name: "Орегано", id: uuid() },
  { type: "Компонент", name: "Зеленый перец", id: uuid() },
  { type: "Компонент", name: "Томаты", id: uuid() },
  { type: "Компонент", name: "Чеснок", id: uuid() },
  { type: "Компонент", name: "Красный перец", id: uuid() },
  { type: "Компонент", name: "Оливки", id: uuid() },
  { type: "Компонент", name: "Маслины", id: uuid() },
  { type: "Компонент", name: "ХМаслиныит", id: uuid() },
  { type: "Компонент", name: "ХиКлубникат", id: uuid() },
  { type: "Компонент", name: "Смесь итальянских трав", id: uuid() },
];
